chce_LAMP_FastCGI.sh - ustawienie ostatniej dostępnej wersji  #161
unkn0w/noobs pull request #178
Opened 2023-09-04 14:53 UTC by mati75

W oparciu o metapakiet php-cli dodałem wyciąganie ostatniej domyślnej wersji i ustawienie jej jako docelowa w apache.

2023-09-04 17:42 UTC, ferexio commented
Dlaczego widzę zdublowane PR?
https://github.com/unkn0w/noobs/pull/178
https://github.com/unkn0w/noobs/pull/180
https://github.com/unkn0w/noobs/pull/179
Który z nich jest do zmergowania?

2023-09-04 17:47 UTC, ferexio commented
> @ferexio zazwyczaj piszę w komentarzach - te z "x" są do poprawnienia

Dla mnie na przykład, dla osoby która robi review, to nie jest jasne :)

2023-09-04 17:59 UTC, loper commented
Błędy w shellchecku - prosimy o poprawienie.

2023-09-05 07:45 UTC, loper requested changes
Wersja nie może być na stałe wpisana: .../ubuntu/**20.04**/packages-microsoft...

2023-09-05 18:06 UTC, mati75 commented
Robię nowy PR bo tutaj się zrobiła sieczka

2023-09-05 18:06 UTC, closed without merging